apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-portfolio
  template:
    metadata:
      labels:
        app: cloud-portfolio
    spec:
      containers:
        - name: cloud-portfolio
          image: shaunsunny/cloud-portfolio:latest   # 👈 Docker Hub image
          ports:
            - containerPort: 3000
